# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-12-12 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.cus_picture
import helpers.director.model_func.cus_fields.richtext


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('cover', helpers.director.model_func.cus_fields.cus_picture.PictureField(max_length=300, verbose_name='封面')),
                ('status', models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=0, verbose_name='在线')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=helpers.director.model_func.cus_fields.richtext.RichtextField(verbose_name='内容'),
        ),
    ]
