# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-24 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.cus_picture
import helpers.director.model_func.cus_fields.richtext


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0002_auto_20191212_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('content', helpers.director.model_func.cus_fields.richtext.RichtextField(verbose_name='内容')),
                ('cover', helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=300, verbose_name='封面')),
                ('status', models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=0, verbose_name='在线')),
                ('kind', models.IntegerField(choices=[(1, '管理系统'), (2, '移动端')], default=0, verbose_name='在线')),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='标题'),
        ),
    ]
