# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-27 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0005_banner_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='连接'),
        ),
    ]
