# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-28 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0006_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
